// INSTAGRAM
export const INSTAGRAM_CLIENT_ID = import.meta.env.VITE_INSTAGRAM_CLIENT_ID;
export const INSTAGRAM_CLIENT_SECRET = import.meta.env.VITE_INSTAGRAM_CLIENT_SECRET;
export const INSTAGRAM_REDIRECT_URI = import.meta.env.VITE_INSTAGRAM_REDIRECT_URI;
export const INSTAGRAM_AUTH_URL = import.meta.env.VITE_INSTAGRAM_AUTH_URL;
export const INSTAGRAM_TOKEN_URL = import.meta.env.VITE_INSTAGRAM_TOKEN_URL;
// FIREBASE
export const FIREBASE_API_KEY = import.meta.env.VITE_FIREBASE_API_KEY;
export const FIREBASE_AUTH_DOMAIN = import.meta.env.VITE_FIREBASE_AUTH_DOMAIN;
export const FIREBASE_PROJECT_ID = import.meta.env.VITE_FIREBASE_PROJECT_ID;
export const FIREBASE_STORAGE_BUCKET = import.meta.env.VITE_FIREBASE_STORAGE_BUCKET;
export const FIREBASE_MESSAGING_SENDER_ID = import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID;
export const FIREBASE_APP_ID = import.meta.env.VITE_FIREBASE_APP_ID;
