export const SET_ACTIVE_MODAL = "SET_ACTIVE_MODAL";
export const TOGGLE_LIKE = "TOGGLE_LIKE";
export const SET_COMMENTS = "SET_COMMENTS";
export const INCREMENT_LIKE_COUNT = "INCREMENT_LIKE_COUNT";
export const ADD_COMMENT = "ADD_COMMENT";
export const SET_USER_PROFILE = "SET_USER_PROFILE";